### ISSUE TITLE
Error: Exponential test statistic requires positive data

### ISSUE THREAD

**Issue by chauzej** [ErasmusMC-CCBC/katdetectr#1]
Hi,

We are trying to use the package katdetectr.

When starting the command line kdVCF <- detectKataegis(genomicVariants = FileX), we systematically have the following error :

Error: BiocParallel errors
  1 remote errors, element index: 5
  19 unevaluated and other errors
  first remote error:
Error in multiple.meanvar.exp(data, mul.method = method, penalty, pen.value, : Exponential test statistic requires positive data

Could you please help us ?

Sincerely.

**Comment by HarmenvdWerken** [comment]
Dear Chauzej,

Thank you for your remark.
Could you please send me the input file you are using to h.vandewerken[at]erasmusmc.nl

All the best,
Harmen

**Comment by daanhazelaar** [comment]
Dear @chauzej 

Thanks for opening this issue! 

I have updated `katdetectr` which should fix your problem. Make sure that you specify the correct reference genome using the refSeq argument in detectKataegis(). 

Please see the code below:
```R
# download the latest version of katdetectr from github
devtools::install_git(url = "https://github.com/ErasmusMC-CCBC/katdetectr")

# load and attach katdetectr
library("katdetectr")

# detect kataegis
kd <- detectKataegis(genomicVariants = "path/to/file.vcf", refSeq = "hg38")

# visualize in a rainfall plot
rainfallPlot(kd)
```

Please let me know if you experience any other problems!

Kind regards,
Daan Hazelaar
