### ISSUE TITLE
VRange input error

### ISSUE THREAD

**Issue by ThomasGro** [ErasmusMC-CCBC/katdetectr#8]
I want to use a VRange object as input and tried it first with your MAF file as source, filtered for "SNP".
Running 'detectKataegis(genomicVariants = vr, aggregateRecords = TRUE)' returns error.
I belief the "sampleNames(vr)" are not used?! which leads to duplicated entries.

>library(VariantAnnotation)
>gr=makeGRangesFromDataFrame(APL_primary.maf,
                            keep.extra.columns=TRUE,
                            ignore.strand=TRUE,
                            seqinfo=NULL,
                            seqnames.field="Chromosome",
                            start.field="Start_Position",
                            end.field="End_Position",
                            starts.in.df.are.0based=TRUE,
                              )
>values(gr) <- data.frame (
  ID = APL_primary.maf$Tumor_Sample_Barcode,
  ref = APL_primary.maf$Reference_Allele,
  alt = APL_primary.maf$Tumor_Seq_Allele2)

>vr=makeVRangesFromGRanges(gr, ref.field='ref', alt.field='alt', sampleNames.field='ID', keep.extra.columns=TRUE)
>genome(seqinfo(vr))='hg19'

> detectKataegis(genomicVariants = vr, aggregateRecords = TRUE)
Fehler in `[[<-`(`*tmp*`, name, value = new("CompressedIntegerList", elementType = "integer",  : 
  165 elements in value to replace 171 elements
> traceback()
8: stop(paste(lv, "elements in value to replace", nrx, "elements"))
7: `[[<-`(`*tmp*`, name, value = new("CompressedIntegerList", elementType = "integer", 
       elementMetadata = NULL, metadata = list(), unlistData = c(28L, 
       96L, 93L, 95L, 92L, 94L, 7L, 49L, 150L, 149L, 27L, 81L, 76L, 
       17L, 78L, 140L, 139L, 138L, 134L, 135L, 42L, 70L, 98L, 97L, 
       58L, 157L, 74L, 85L, 19L, 151L, 152L, 64L, 37L, 87L, 148L, 
       11L, 16L, 3L, 5L, 6L, 53L, 77L, 114L, 65L, 36L, 156L, 155L, 
       51L, 23L, 79L, 32L, 26L, 61L, 30L, 12L, 66L, 67L, 39L, 43L, 
       153L, 9L, 45L, 100L, 118L, 119L, 117L, 50L, 44L, 144L, 145L, 
       20L, 18L, 22L, 31L, 21L, 35L, 29L, 154L, 62L, 41L, 163L, 
       161L, 162L, 82L, 169L, 168L, 83L, 166L, 167L, 171L, 170L, 
       84L, 165L, 164L, 159L, 54L, 130L, 141L, 142L, 59L, 10L, 99L, 
       120L, 124L, 125L, 121L, 24L, 63L, 128L, 127L, 126L, 52L, 
       129L, 71L, 13L, 147L, 146L, 69L, 107L, 102L, 34L, 33L, 106L, 
       104L, 109L, 105L, 108L, 132L, 72L, 101L, 112L, 113L, 56L, 
       80L, 143L, 111L, 15L, 75L, 14L, 68L, 133L, 131L, 48L, 1L, 
       25L, 46L, 2L, 90L, 91L, 60L, 89L, 55L, 115L, 116L, 57L, 88L, 
       40L, 73L, 38L, 158L, 110L, 47L, 4L, 86L, 8L), partitioning = new("PartitioningByEnd", 
           end = 1:165, NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
           metadata = list())))
6: `[[<-`(`*tmp*`, name, value = new("CompressedIntegerList", elementType = "integer", 
       elementMetadata = NULL, metadata = list(), unlistData = c(28L, 
       96L, 93L, 95L, 92L, 94L, 7L, 49L, 150L, 149L, 27L, 81L, 76L, 
       17L, 78L, 140L, 139L, 138L, 134L, 135L, 42L, 70L, 98L, 97L, 
       58L, 157L, 74L, 85L, 19L, 151L, 152L, 64L, 37L, 87L, 148L, 
       11L, 16L, 3L, 5L, 6L, 53L, 77L, 114L, 65L, 36L, 156L, 155L, 
       51L, 23L, 79L, 32L, 26L, 61L, 30L, 12L, 66L, 67L, 39L, 43L, 
       153L, 9L, 45L, 100L, 118L, 119L, 117L, 50L, 44L, 144L, 145L, 
       20L, 18L, 22L, 31L, 21L, 35L, 29L, 154L, 62L, 41L, 163L, 
       161L, 162L, 82L, 169L, 168L, 83L, 166L, 167L, 171L, 170L, 
       84L, 165L, 164L, 159L, 54L, 130L, 141L, 142L, 59L, 10L, 99L, 
       120L, 124L, 125L, 121L, 24L, 63L, 128L, 127L, 126L, 52L, 
       129L, 71L, 13L, 147L, 146L, 69L, 107L, 102L, 34L, 33L, 106L, 
       104L, 109L, 105L, 108L, 132L, 72L, 101L, 112L, 113L, 56L, 
       80L, 143L, 111L, 15L, 75L, 14L, 68L, 133L, 131L, 48L, 1L, 
       25L, 46L, 2L, 90L, 91L, 60L, 89L, 55L, 115L, 116L, 57L, 88L, 
       40L, 73L, 38L, 158L, 110L, 47L, 4L, 86L, 8L), partitioning = new("PartitioningByEnd", 
           end = 1:165, NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
           metadata = list())))
5: `$<-`(`*tmp*`, "revmap", value = new("CompressedIntegerList", 
       elementType = "integer", elementMetadata = NULL, metadata = list(), 
       unlistData = c(28L, 96L, 93L, 95L, 92L, 94L, 7L, 49L, 150L, 
       149L, 27L, 81L, 76L, 17L, 78L, 140L, 139L, 138L, 134L, 135L, 
       42L, 70L, 98L, 97L, 58L, 157L, 74L, 85L, 19L, 151L, 152L, 
       64L, 37L, 87L, 148L, 11L, 16L, 3L, 5L, 6L, 53L, 77L, 114L, 
       65L, 36L, 156L, 155L, 51L, 23L, 79L, 32L, 26L, 61L, 30L, 
       12L, 66L, 67L, 39L, 43L, 153L, 9L, 45L, 100L, 118L, 119L, 
       117L, 50L, 44L, 144L, 145L, 20L, 18L, 22L, 31L, 21L, 35L, 
       29L, 154L, 62L, 41L, 163L, 161L, 162L, 82L, 169L, 168L, 83L, 
       166L, 167L, 171L, 170L, 84L, 165L, 164L, 159L, 54L, 130L, 
       141L, 142L, 59L, 10L, 99L, 120L, 124L, 125L, 121L, 24L, 63L, 
       128L, 127L, 126L, 52L, 129L, 71L, 13L, 147L, 146L, 69L, 107L, 
       102L, 34L, 33L, 106L, 104L, 109L, 105L, 108L, 132L, 72L, 
       101L, 112L, 113L, 56L, 80L, 143L, 111L, 15L, 75L, 14L, 68L, 
       133L, 131L, 48L, 1L, 25L, 46L, 2L, 90L, 91L, 60L, 89L, 55L, 
       115L, 116L, 57L, 88L, 40L, 73L, 38L, 158L, 110L, 47L, 4L, 
       86L, 8L), partitioning = new("PartitioningByEnd", end = 1:165, 
           NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
           metadata = list())))
4: `$<-`(`*tmp*`, "revmap", value = new("CompressedIntegerList", 
       elementType = "integer", elementMetadata = NULL, metadata = list(), 
       unlistData = c(28L, 96L, 93L, 95L, 92L, 94L, 7L, 49L, 150L, 
       149L, 27L, 81L, 76L, 17L, 78L, 140L, 139L, 138L, 134L, 135L, 
       42L, 70L, 98L, 97L, 58L, 157L, 74L, 85L, 19L, 151L, 152L, 
       64L, 37L, 87L, 148L, 11L, 16L, 3L, 5L, 6L, 53L, 77L, 114L, 
       65L, 36L, 156L, 155L, 51L, 23L, 79L, 32L, 26L, 61L, 30L, 
       12L, 66L, 67L, 39L, 43L, 153L, 9L, 45L, 100L, 118L, 119L, 
       117L, 50L, 44L, 144L, 145L, 20L, 18L, 22L, 31L, 21L, 35L, 
       29L, 154L, 62L, 41L, 163L, 161L, 162L, 82L, 169L, 168L, 83L, 
       166L, 167L, 171L, 170L, 84L, 165L, 164L, 159L, 54L, 130L, 
       141L, 142L, 59L, 10L, 99L, 120L, 124L, 125L, 121L, 24L, 63L, 
       128L, 127L, 126L, 52L, 129L, 71L, 13L, 147L, 146L, 69L, 107L, 
       102L, 34L, 33L, 106L, 104L, 109L, 105L, 108L, 132L, 72L, 
       101L, 112L, 113L, 56L, 80L, 143L, 111L, 15L, 75L, 14L, 68L, 
       133L, 131L, 48L, 1L, 25L, 46L, 2L, 90L, 91L, 60L, 89L, 55L, 
       115L, 116L, 57L, 88L, 40L, 73L, 38L, 158L, 110L, 47L, 4L, 
       86L, 8L), partitioning = new("PartitioningByEnd", end = 1:165, 
           NAMES = NULL, elementType = "ANY", elementMetadata = NULL, 
           metadata = list())))
3: .reduceOverlappingVariants(genomicVariantsImported)
2: .processGenomicVariants(genomicVariantsImported)
1: detectKataegis(genomicVariants = vr, aggregateRecords = TRUE)

[vr.zip](https://github.com/ErasmusMC-CCBC/katdetectr/files/13618049/vr.zip)

**Comment by daanhazelaar** [comment]
Hi @ThomasGro,

Thank you for reaching out! I just checked the vr file you shared. It looks like the start locations of the variants in your data are -1 from their end location (see image).
![Screenshot 2023-12-08 at 17 35 41](https://github.com/ErasmusMC-CCBC/katdetectr/assets/55545896/fe9dd3ed-67be-4c55-bb15-086132c25ba1)
)

I was not aware that this was allowed in a vRanges object. Seems also strange to me that the start location lies behind the end location of the variant. Or is there a reason for this?

I'll check how to fix this and add some tests for this particular problem in the future. For now, the following works on my machine:
```R
vr2 <- vr |> 
    as_tibble() |> 
    mutate(
        start = start -1
    ) |> 
    GenomicRanges::makeGRangesFromDataFrame(keep.extra.columns = TRUE) |> 
    VariantAnnotation::makeVRangesFromGRanges()

kd <- detectKataegis(vr2, aggregateRecords = TRUE)
```

**Comment by ThomasGro** [comment]
Thank you, for the investigation.

The point is that I set for your MAF test file:
makeGRangesFromDataFrame(starts.in.df.are.0based=TRUE)

This led to the shift in the start position.
However, I belief MAF files usually are 0-based, whereas VCFs are 1-based.

Best,
Thomas

**Comment by daanhazelaar** [comment]
Hi @ThomasGro,

Aah thank you for the explanation! Do you perhaps have a recommendation for how I should deal with this? 

I was thinking about adding tests that let the user now that the start location >= end location. But if this a common way of describing variant locations perhaps I should incorporate this in a different way? Any suggestions are much appreciated!

Kind regards,
Daan Hazelaar

**Comment by ThomasGro** [comment]
Hello Daan,
you may want to look here: https://genomewiki.ucsc.edu/index.php/Coordinate_Transforms

The 0-based system has SNV coordinates like
start = 0
end =1
Whereas 1-based systems has SNV coordinates like
                start = 1
                end = 1

Length of the range of 0-based systems is (end-start) and in 1-base systems (end-(start-1)).

Best,
Thomas
